// Generated by CoffeeScript 1.3.3

ce.module("activity.participants", function(self, ce, Backbone, Marionette, $, _) {
  self.on("bottombar_loaded", function() {
    ce.log.info("participants: bottom bar loaded");
  });
  self.on("collection_rendered", function() {
    return ce.log.info("participants: collection rendered");
  });
  self.on("filter_loaded", function() {
    ce.log.info("participants: filter loaded");
  });
  self.on("page_loaded", function() {
    ce.log.info("participants: page ready");
  });
  self.on("participants_filtered", function(name) {
    return ce.log.info("participants: filter by " + name);
  });
  self.on("participant_saved", function(data) {
    ce.log.info("participant: saved");
  });
  self.on("participants_loaded", function() {
    ce.log.info("participants: loaded");
  });
  self.on("selectallcheckbox_rendered", function() {
    return ce.log.info("participants: select all checkbox loaded");
  });
  self.on("statusdate_saved", function() {
    ce.log.info("participant: status date saved");
  });
  self.on("topbar_loaded", function() {
    ce.log.info("participants: top bar loaded");
  });
  return self.on("viewable_participant_date_changed", function() {
    ce.log.info("participants: viewable date changed");
    return;
  });
});
