// Generated by CoffeeScript 1.3.3
/*=================================================
*  Foundry v0.1
*  (c) 2012 Joshua F. Rountree, Justin Slamka, University of Cincinnati
*  =================================================
*  Foundry may be freely distributed under the MIT license.
*  For all details and documentation:
*  https://github.com/JoshuaIRL/foundry.coffee 
*  =================================================
*/

var Backbone, Component, SKIP_PROPERTIES, include, __extend,
  __hasProp = {}.hasOwnProperty,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __slice = [].slice,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Backbone = require("backbone");

SKIP_PROPERTIES = ["constructor", "extended", "included", "prototype"];

__extend = function(object, mixin) {
  var method, name, _results;
  _results = [];
  for (name in mixin) {
    if (!__hasProp.call(mixin, name)) continue;
    method = mixin[name];
    if (__indexOf.call(SKIP_PROPERTIES, name) < 0) {
      _results.push(object[name] = method);
    }
  }
  return _results;
};

include = function() {
  var mixin, mixins, object, _i, _len, _results;
  object = arguments[0], mixins = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  if (object.prototype == null) {
    throw new TypeError;
  }
  _results = [];
  for (_i = 0, _len = mixins.length; _i < _len; _i++) {
    mixin = mixins[_i];
    if (mixin.prototype != null) {
      __extend(object, mixin);
      __extend(object.prototype, mixin.prototype);
    } else {
      __extend(object.prototype, mixin);
    }
    if (mixin.included != null) {
      _results.push(mixin.included(object));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

/*
* Base class for adding mixins, Ruby style, to CoffeeScript
* classes. There is no support for super. This essentially
* just copies over properties from objects and classes.
*
*/


Component = (function(_super) {

  __extends(Component, _super);

  function Component() {
    return Component.__super__.constructor.apply(this, arguments);
  }

  Component.include = function() {
    var mixins;
    mixins = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return include.apply(null, [this].concat(__slice.call(mixins)));
  };

  return Component;

})(Backbone.View);

module.setExports(Component);
