// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; },
  __slice = [].slice,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define("foundry/module", function(require) {
  var Module, SKIP_PROPERTIES, extend, include, __extend;
  SKIP_PROPERTIES = ["constructor", "extended", "included", "prototype"];
  __extend = function(object, mixin) {
    var method, name, _results;
    _results = [];
    for (name in mixin) {
      if (!__hasProp.call(mixin, name)) continue;
      method = mixin[name];
      if (__indexOf.call(SKIP_PROPERTIES, name) < 0) {
        _results.push(object[name] = method);
      }
    }
    return _results;
  };
  extend = function() {
    var mixin, mixins, object, _i, _len, _ref, _results;
    object = arguments[0], mixins = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    _results = [];
    for (_i = 0, _len = mixins.length; _i < _len; _i++) {
      mixin = mixins[_i];
      __extend(object, (_ref = mixin.prototype) != null ? _ref : mixin);
      if (mixin.extended != null) {
        _results.push(mixin.extended(object));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };
  include = function() {
    var mixin, mixins, object, _i, _len, _results;
    object = arguments[0], mixins = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (object.prototype == null) {
      throw new TypeError;
    }
    _results = [];
    for (_i = 0, _len = mixins.length; _i < _len; _i++) {
      mixin = mixins[_i];
      if (mixin.prototype != null) {
        __extend(object, mixin);
        __extend(object.prototype, mixin.prototype);
      } else {
        __extend(object.prototype, mixin);
      }
      if (mixin.included != null) {
        _results.push(mixin.included(object));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };
  Module = (function(_super) {

    __extends(Module, _super);

    function Module() {
      return Module.__super__.constructor.apply(this, arguments);
    }

    /*
        * Calls extends method, with `this` as the object.
        * Not to be confused with "extend" which is the way you extend an Object in Backbone
        * This is the only instance of misleading functions / symantecs within Foundry
    */


    Module["extends"] = function() {
      var mixins;
      mixins = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return extend.apply(null, [this].concat(__slice.call(mixins)));
    };

    Module.includes = function() {
      var mixins;
      mixins = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return include.apply(null, [this].concat(__slice.call(mixins)));
    };

    return Module;

  })(Backbone.View);
  return module.setExports(Module);
});
