// Generated by CoffeeScript 1.3.3
/*=================================================
*  Foundry v0.1
*  (c) 2012 Joshua F. Rountree, Justin Slamka, University of Cincinnati
*  =================================================
*  Foundry may be freely distributed under the MIT license.
*  For all details and documentation:
*  https://github.com/JoshuaIRL/foundry.coffee 
*  =================================================
*/

var Component, Widget,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require("foundry/component");

Widget = (function(_super) {

  __extends(Widget, _super);

  function Widget() {
    return Widget.__super__.constructor.apply(this, arguments);
  }

  return Widget;

})(Component);

module.setExports(Widget);
