// Generated by CoffeeScript 1.3.3

ce.module("Views.Activity_participants", function(self, ce, Backbone, Marionette, $, _) {
  return self.EditView = Backbone.Marionette.ItemView.extend({
    template: "activity_participants/edit"
  });
});
