// Generated by CoffeeScript 1.3.3

ce.module("Views.Activity_participants", function(self, ce, Backbone, Marionette, $, _) {
  return self.IndexView = Backbone.Marionette.CompositeView.extend({
    tagName: "table",
    itemView: self.RowView,
    template: "activity_participants/index",
    events: {
      "click .new": "newRecord"
    },
    appendHtml: function(collectionView, itemView) {
      return collectionView.$(".activity_participants").append(itemView.el);
    },
    newRecord: function() {}
  });
});
