// Generated by CoffeeScript 1.3.3

ce.module("Views.Activity_participants", function(self, ce, Backbone, Marionette, $, _) {
  return self.ShowView = Backbone.Marionette.ItemView.extend({
    template: "activity_participants/show"
  });
});
