source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'bundler'
gem 'rb-fsevent', '~> 0.9.1'
gem 'sprockets', '~> 2.5'
gem 'therubyracer'
gem 'less'
gem 'coffee-script'
gem 'uglifier'
gem 'ejs'
gem 'eco'