// Generated by CoffeeScript 1.3.3

self.load = function(params) {
  self.userPrefs = {
    actListHeight: params.legacy.cActListHeight,
    actListOpen: params.legacy.cActListOpen,
    actListPosX: params.legacy.cActListPosX,
    actListPosY: params.legacy.cActListPosY,
    actListWidth: params.legacy.cActListWidth,
    actNotesOpen: params.legacy.cActNotesOpen,
    actNotesPosX: params.legacy.cActNotesPosX,
    actNotesPosY: params.legacy.cActNotesPosY
  };
  self.legacy = params.legacy;
  return self.model = new models.Activity(params.modelData);
};

exports.activity = self;
