// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define("app/user", ["require", "backbone", "jquery"], function(require, Backbone, $) {
  var User;
  return User = (function(_super) {

    __extends(User, _super);

    function User(params) {
      this.model = new self.Model(params);
      this.trigger("loaded");
      this.isLoggedIn();
      return;
      $(function() {
        $(".loginLink").click(function(ev) {
          user.login({});
          ev.preventDefault();
          return false;
        });
      });
      return;
      module.setExports(user);
    }

    User.prototype.Model = require("app/models/Person");

    return User;

  })(Backbone.View);
});
