// Generated by CoffeeScript 1.3.3

define("app/activity", ["require", "backbone"], function(require, Backbone) {
  var activity;
  activity = {};
  activity.Model = require("app/models/activity");
  activity.load = function(params) {
    activity.userPrefs = {
      actListHeight: params.legacy.cActListHeight,
      actListOpen: params.legacy.cActListOpen,
      actListPosX: params.legacy.cActListPosX,
      actListPosY: params.legacy.cActListPosY,
      actListWidth: params.legacy.cActListWidth,
      actNotesOpen: params.legacy.cActNotesOpen,
      actNotesPosX: params.legacy.cActNotesPosX,
      actNotesPosY: params.legacy.cActNotesPosY
    };
    activity.legacy = params.legacy;
    return activity.model = new activity.Model(params.modelData);
  };
  module.setExports(activity);
});
