// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["common"], function(common) {
  var App, app;
  App = (function(_super) {

    __extends(App, _super);

    function App() {
      this.pagelets = {};
      this.models = {};
      this.views = {};
      this.collections = {};
    }

    App.prototype.start = function() {};

    return App;

  })(Backbone.View);
  Backbone.Paginator.clientPager.prototype.whereExpanded = function(attrs) {
    return _.filter(this.origModels, function(model) {
      var key;
      for (key in attrs) {
        if (attrs[key] !== model.get(key)) {
          return false;
        }
      }
      return true;
    });
  };
  /*!
  CE APP
  */

  app = new App;
  /*! SETUP BASE CLASSES TO EXTEND FROM
  */

  app.Collection = require("Collection");
  /*! PAGELET CLASS - Handles each tier of the app, and loads it's _js.cfm and pulls in any modules needed for that page using AJAX now.
  */

  ce.Pagelet = (function() {

    function Pagelet() {}

    return Pagelet;

  })();
  /*! VIEW CLASS
  */

  ce.View = (function(_super) {

    __extends(View, _super);

    function View() {
      return View.__super__.constructor.apply(this, arguments);
    }

    return View;

  })(Backbone.View);
  if (window.console === void 0) {
    window.console = {
      log: function() {}
    };
  }
  console.log('app: start');
  app.start();
  return app;
});
