// Generated by CoffeeScript 1.3.3
'use strict';

requirejs.config({
  baseUrl: 'javascripts/app',
  paths: {
    backbone: '../libs/backbone',
    underscore: '../libs/underscore',
    'backbone.paginator': '../libs/backbone/backbone.paginator'
  },
  shim: {
    'backbone.paginator': ['backbone']
  }
});

require(["application", "backbone", "underscore", "log", "collections", "models", "views"], function(App, Backbone, _, log) {
  window.ce = new App;
  return $(function() {
    ce.start();
    log.info("app: start");
  });
});
