// Generated by CoffeeScript 1.3.3
var Backbone, Model,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Backbone = require("backbone");

Model = (function(_super) {

  __extends(Model, _super);

  function Model() {}

  return Model;

})(Backbone.Model);

module.setExports(Model);
