// Generated by CoffeeScript 1.3.3

Inject.reset();

Inject.setModuleRoot("/javascripts/");

Inject.addRule(/^jquery$/, {
  path: "vendor/jquery/jquery",
  pointcuts: {
    after: function() {
      module.setExports(jQuery.noConflict());
    }
  }
});

Inject.addRule(/^underscore$/, {
  path: "vendor/underscore/underscore"
});

Inject.addRule(/^backbone$/, {
  path: "vendor/backbone/backbone"
});

Inject.addRule(/^backbone.paginator$/, {
  path: "vendor/backbone/backbone.paginator"
});
