// Generated by CoffeeScript 1.3.3
var Backbone, Component, User, auth, events,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require("foundry/component");

auth = require("app/user/auth");

events = {};

Backbone = require("backbone");

User = (function(_super) {

  __extends(User, _super);

  User.include(auth);

  User.prototype.initialize = function() {};

  function User(params) {
    this.Model = require("app/model");
    this.model = new this.Model(params);
    return;
  }

  return User;

})(Component);

module.setExports(User);
