// Generated by CoffeeScript 1.3.3
var App, Backbone, app,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

console.log("app");

Backbone = require("backbone");

App = (function(_super) {

  __extends(App, _super);

  function App() {
    this._core = {};
    this.models = require("app/models");
    this.collections = require("app/collections");
    this.activity = require("app/activity");
    this.person = require("app/person");
    this.user = require("app/user");
  }

  return App;

})(Backbone.View);

app = new App();

Backbone.Paginator.clientPager.prototype.whereExpanded = function(attrs) {
  return _.filter(this.origModels, function(model) {
    var key;
    for (key in attrs) {
      if (attrs[key] !== model.get(key)) {
        return false;
      }
    }
    return true;
  });
};

Backbone.emulateJSON = true;

app.on("loaded", function() {
  return ce.log.info("app: started");
});

module.setExports(app);
