// Generated by CoffeeScript 1.3.3
var user;

user = {};

user.load = function(params) {
  self.model = new self.Model(params);
  self.trigger("loaded");
  self.isLoggedIn();
};

$(function() {
  $(".loginLink").click(function(ev) {
    self.login({});
    ev.preventDefault();
    return false;
  });
});

return;

exports.user = self;
