// Generated by CoffeeScript 1.3.3
(function() {

  ce.module("activity.participants", function(self, ce, Backbone, Marionette, $, _) {
    return self.Topbar = Backbone.View.extend({
      template: ce.templates.get("activity_participants-topbar"),
      render: function() {
        return this.$el.html(_.template(this.template));
      }
    });
  });

}).call(this);
