// Generated by CoffeeScript 1.3.3

ce.module("_core.views.main", function(self, ce, Backbone, Marionette, $, _) {
  return self.IndexView = Backbone.Marionette.CompositeView.extend({
    tagName: "table",
    itemView: self.RowView,
    template: "main/index",
    events: {
      "click .new": "newRecord"
    },
    appendHtml: function(collectionView, itemView) {
      return collectionView.$(".main").append(itemView.el);
    },
    newRecord: function() {}
  });
});
