// Generated by CoffeeScript 1.3.3
(function() {

  ce.module("activity.credit_requests", function(self, ce, Backbone, Marionette, $, _) {
    return self.on("loaded", function() {
      return ce.log.info("credit_requests: loaded");
    });
  });

}).call(this);
