// Generated by CoffeeScript 1.3.3

ce.module("Routers", function(self, ce, Backbone, Marionette, $, _) {
  return self.Activity_participants = Backbone.Marionette.AppRouter.extend({
    appRoutes: {
      "": "index",
      "activity_participants/:id/show": "show",
      "activity_participants/:id/edit": "edit"
    }
  });
});
