// Generated by CoffeeScript 1.3.3

ce.module("_core.routers", function(self, ce, Backbone, Marionette, $, _) {
  return self.Sessions = Backbone.Marionette.AppRouter.extend({
    appRoutes: {
      "": "index",
      "sessions/:id/show": "show",
      "sessions/:id/edit": "edit"
    }
  });
});
