// Generated by CoffeeScript 1.3.3
var ce;

window.ce = window.ce || {};

ce = new Backbone.Marionette.Application();

ce.module("_core");

ce.module("activity");

ce.module("person");

ce.addRegions({
  page: "#page",
  subpage: ".contentBar div.content-container"
});

ce.addInitializer(function(options) {
  return ce.trigger("loaded");
});

Backbone.Paginator.clientPager.prototype.whereExpanded = function(attrs) {
  return _.filter(this.origModels, function(model) {
    var key;
    for (key in attrs) {
      if (attrs[key] !== model.get(key)) {
        return false;
      }
    }
    return true;
  });
};

ce.on("loaded", function() {
  return ce.log.info("app: started");
});
