// Generated by CoffeeScript 1.3.3

ce.module("creditinator", function(self, ce, Backbone, Marionette, $, _, models, log, user) {
  self.views.steps.Start = self.views.StepView.extend({
    wheelsAction: "start",
    nextStep: function() {
      if (user.isLoggedIn()) {
        return "finish";
      } else {
        return "identify";
      }
    },
    prevStep: "",
    stepTitle: "Welcome!",
    stepSubTitle: "Enter the code you were provided at the live event.",
    beforeGoToNext: function() {
      $.ajax({
        url: '/creditinator/checkcode'
      });
      return true;
    }
  });
}, ce._core.models, ce.log, ce.user);
