// Generated by CoffeeScript 1.3.3

ce.module("creditinator", function(self, ce, Backbone, Marionette, $, _, models, log, user) {
  self.steps.CodeEntry = self.views.StepView.extend({
    eventCode: $(".eventCode"),
    checkCode: function(eventCode) {},
    isStepValid: function() {
      return false;
    },
    isCompleted: function() {
      return false;
    },
    nextStep: function() {
      if (user.isLoggedIn()) {
        return 'confirmed';
      } else {
        return 'auth';
      }
    },
    events: {
      ".continueBtn click": "saveCode"
    }
  });
}, ce._core.models, ce.log, ce.user);
