// Generated by CoffeeScript 1.3.3
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define("app", ["require", "backbone", "jquery", "bootstrap"], function(require, Backbone, $, bootstrap) {
  var App;
  App = (function(_super) {

    __extends(App, _super);

    function App() {
      this.$win = window;
      this.$doc = this.$win.document;
      this.$body = this.$doc.body;
      this.el = $("#app");
      this.Model = require("app/model");
      this.Collection = require("app/collection");
      this.User = require("app/user");
      this.log = require("logger");
      this.log.info("app: started");
    }

    return App;

  })(Backbone.View);
  console.log("test");
  return module.setExports(App);
});
