// Generated by CoffeeScript 1.3.3
var $, App, Backbone, app,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

$ = require("jquery");

Backbone = require("backbone");

require.ensure(["libs/backbone/backbone.paginator"], function() {
  return require.run("libs/backbone/backbone.paginator");
});

require("bootstrap");

console.log(Backbone);

App = (function(_super) {

  __extends(App, _super);

  function App() {
    this.$win = window;
    this.$doc = this.$win.document;
    this.$body = this.$doc.body;
    this.el = $("#app");
    this.Model = require("app/model");
    this.Collection = require("app/collection");
  }

  return App;

})(Backbone.View);

app = new App();

Backbone.emulateJSON = true;

module.setExports(app);
