// Generated by CoffeeScript 1.3.3

Inject.reset();

Inject.setModuleRoot("/javascripts/");

Inject.addRule(/^jquery$/, {
  path: "libs/jquery",
  pointcuts: {
    after: function() {
      module.setExports(jQuery.noConflict());
    }
  }
});

Inject.addRule(/^bootstrap$/, {
  path: "libs/bootstrap",
  pointcuts: {
    before: function() {
      var $;
      return $ = require("jquery");
    }
  }
});

Inject.addRule(/app\/models\//, {
  path: function(module) {
    return module.replace("app/models", "app/base/models");
  }
});

Inject.addRule(/^app\/collections\//, {
  path: function(module) {
    return module.replace("app/collections", "app/base/collections");
  }
});

Inject.addRule(/^underscore$/, {
  path: "libs/underscore"
});

Inject.addRule(/^backbone$/, {
  path: "libs/backbone"
});
