// Generated by CoffeeScript 1.3.3

ce.module("creditinator", function(self, ce, Backbone, Marionette, $, _, models, log, user) {
  self.views.steps.Identify = self.views.StepView.extend({
    wheelsAction: "identify",
    wheelsControllerPath: "/creditinator/",
    wheelsFullPath: function() {
      return this.wheelsControllerPath + "" + this.wheelsAction;
    },
    isStepValid: function() {
      return false;
    },
    currentStep: "identify",
    nextStep: "confirm",
    prevStep: "start",
    stepTitle: "Okay, now let's identify you.",
    stepSubTitle: "It's quick and painless!",
    beforeGoToNext: function() {
      return true;
    }
  });
}, ce._core.models, ce.log, ce.user);
