// Generated by CoffeeScript 1.3.3

ce.module("_core.collections", function(self, ce, Backbone, Marionette, $, _, models) {
  return self.People = Backbone.Collection.extend({
    url: '/people/',
    model: models.Person
  });
}, ce._core.models);
