// Generated by CoffeeScript 1.3.3

ce.module("ui", function(self, ce, Backbone, Marionette, $, _) {
  return self.dialog = Backbone.Marionette.Region.extend({
    el: "#dialog",
    constructor: function() {
      _.bindAll(this);
      Backbone.Marionette.Region.prototype.constructor.apply(this, arguments_);
      this.on("view:show", this.showDialog, this);
    },
    getEl: function(selector) {
      var $el;
      $el = $(selector).dialog();
      $el.on("hidden", this.close);
    },
    showDialog: function(view) {
      view.on("close", this.hideDialog, this);
      this.$el.dialog(view);
      this.$el.dialog("open");
    },
    hideDialog: function() {
      this.$el.dialog("close");
    }
  });
});

ce.addRegions({
  dialog: ce.ui.dialog
});
