// Generated by CoffeeScript 1.3.3

ce.module("activity.participants", function(self, ce, Backbone, Marionette, $, _, models) {
  self.List = Backbone.View.extend({
    initialize: function() {
      var coll;
      coll = this.collection;
      coll.on("add", this.addOne, this);
      coll.on("reset", this.addAll, this);
      coll.on("remove", this.render, this);
      ce.ui.on("filter_filtered", this.render, this);
      self.on("pager_next", this.render, this);
      self.on("pager_prev", this.render, this);
      self.on("page_loaded", this.render, this);
      self.on("page_reload", this.reload, this);
      ce.ui.on("selectallcheckbox_deselectall selectallcheckbox_deselectvisible", this.reload, this);
      coll.fetch({
        success: function() {
          coll.pager();
          self.trigger("data_loaded");
        },
        silent: true
      });
    },
    addAll: function() {
      this.$el.empty();
      if (typeof self.rows === "undefined") {
        self.rows = [];
      } else {
        self.rows = [];
      }
      this.collection.each(this.addOne);
    },
    addOne: function(viewModel) {
      var row;
      viewModel.set({
        FULLNAME: viewModel.get("FIRSTNAME") + " " + viewModel.get("LASTNAME")
      });
      row = new self.Row({
        model: viewModel
      });
      self.rows.push(row);
      $(".js-attendee-rows").append(row.render().el);
    },
    render: function() {
      return self.trigger("collection_rendered");
    },
    reload: function() {
      this.collection.goTo(this.collection.currentPage);
      return self.trigger("page_reloaded");
    }
  });
}, ce._core.models);
