// Generated by CoffeeScript 1.3.3

ce.module("activity.participants", function(self, ce, Backbone, Marionette, $, _, models) {
  return self.List = Backbone.View.extend({
    template: ce.templates.get("activity_participants-table"),
    rowEl: ".js-attendee-rows",
    className: "activity_participants-page",
    initialize: function() {
      var coll;
      coll = this.collection;
      coll.on("add", this.addOne, this);
      coll.on("all", this.render, this);
      coll.on("reset", this.addAll, this);
      coll.fetch({
        success: function() {
          coll.pager();
          self.trigger("data_loaded");
        },
        silent: true
      });
    },
    model: models.Activity_participant,
    render: function() {
      this.$el.html(_.template(this.template));
      return this.collection.all();
    },
    addAll: function() {
      this.$el.empty;
      this.collection.each(this.addOne);
    },
    addOne: function() {
      var view;
      view = new self.Row();
      $(this.rowEl).append(view.render());
    }
  });
}, ce._core.models);
