// Generated by CoffeeScript 1.3.3

ce.module("activity.participants", function(self, ce, Backbone, Marionette, $, _) {
  return self.Topbar = Backbone.View.extend({
    template: "activity_participants-topbar",
    render: function() {
      var _temp;
      _temp = _.template(ce.templates.get(this.template));
      this.$el.html(_temp);
      self.trigger("topbar_loaded");
    }
  });
});
