// Generated by CoffeeScript 1.3.3

ce.module("_core.views.credit_requests", function(self, ce, Backbone, Marionette, $, _) {
  return self.EditView = Backbone.Marionette.ItemView.extend({
    template: "credit_requests/edit"
  });
});
