// Generated by CoffeeScript 1.3.3
/*

HOW TO INIT LOADER
self.loader = new ce.ui.Loader
 	el: WHERE THE ELEMENT WILL ATTACH TO
 	parentEl: THE ELEMENT CONTAINING THE PAGE CONTENT || $(".content-container") is the pagelet for tier3
*/

ce.module("ui", function(self, ce, Backbone, Marionette, $, _) {
  self.Loader = Backbone.View.extend({
    template: "ui-loader",
    className: "loader",
    initialize: function() {
      self.on("loader_start", this.start, this);
      self.on("loader_stop", this.stop, this);
    },
    render: function() {
      var _temp;
      _temp = _.template(ce.templates.get(this.template));
      if (typeof this.options.parentEl !== "undefined") {
        this.options.parentEl.hide();
      }
      this.$el.prepend(_temp);
      self.trigger("loader_loaded");
    },
    start: function() {
      this.render();
      self.trigger("loader_started");
    },
    stop: function() {
      if (typeof this.options.parentEl !== "undefined") {
        this.options.parentEl.show();
      }
      $("." + this.className).remove();
      self.trigger("loader_stopped");
    }
  });
});
