// Generated by CoffeeScript 1.3.3

ce.module("ui", function(self, ce, Backbone, Marionette, $, _) {
  self.Loader = Backbone.View.extend({
    template: _.template(ce.templates.get("ui-loader")),
    className: "loader",
    initialize: function() {
      self.on("loader_start", this.start, this);
      self.on("loader_stop", this.stop, this);
    },
    render: function() {
      if (typeof this.options.parentEl !== "undefined") {
        this.options.parentEl.hide();
      }
      this.$el.prepend(this.template);
      self.trigger("loader_loaded");
    },
    start: function() {
      this.render();
      self.trigger("loader_started");
    },
    stop: function() {
      if (typeof this.options.parentEl !== "undefined") {
        this.options.parentEl.show();
      }
      $("." + this.className).remove();
      self.trigger("loader_stopped");
    }
  });
});
