// Generated by CoffeeScript 1.3.3
var Component, User,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Component = require("foundry/component");

User = (function(_super) {

  __extends(User, _super);

  function User() {
    this.on("loggedIn", function() {
      ce.log.info("user: logged in");
    });
    this.on("loggedOut", function() {
      ce.log.warn("user: logged out");
    });
    this.on("loaded", function() {
      ce.log.info("user: init");
    });
  }

  return User;

})(Component);

module.setExports(User);
