// Generated by CoffeeScript 1.3.3

define("app/user/signup", ["require", "backbone", "jquery"], function(require, Backbone, $) {
  var self;
  self = {};
  self.views.SignupForm = Backbone.View.extend({
    el: "#frmRegister",
    render: function() {
      var view;
      view = this;
    },
    events: {
      "change input": "change",
      "click .cancel": "cancel",
      "submit": "submitLogin"
    },
    change: function(event) {
      return this;
    },
    submitSignup: function(params) {
      var $form, view;
      view = this;
      $form = $(view.el).find('form');
      return $form.ajaxSubmit({
        dataType: 'json',
        success: function(data) {
          if (data.STATUS) {
            self.load(data.PAYLOAD);
            view.close();
          } else {
            $(view.el).find('.flash').text("Login failed!");
          }
          return false;
        }
      });
    },
    cancel: function() {}
  });
  return;
  return module.setExports(self);
});
