// Generated by CoffeeScript 1.3.3

ce.module("user", function(self, ce, Backbone, Marionette, $, _) {
  self.isLoggedIn = function() {
    if (self.model.get("loggedIn")) {
      self.trigger("loggedIn");
      return true;
    } else {
      self.trigger("loggedOut");
      return false;
    }
  };
  self.loginView = Backbone.View.extend({
    tagName: "div",
    className: "",
    render: function() {
      var view;
      view = this;
      $.ajax({
        url: "/login",
        type: "post",
        success: function(data) {
          $(view.el).html(data);
          return this;
        }
      });
    }
  });
  self.login = function(params) {
    var view;
    view = new self.loginView();
    ce.dialog.show(view);
    self.trigger("loggedIn");
  };
  self.logout = function(params) {
    self.trigger("loggedOut");
  };
});
