// Generated by CoffeeScript 1.3.3
(function() {

  ce.module("global.ajax", function(self, ce, Backbone, Marionette, $, _) {
    return $(function() {
      $(document).on("click", ".projectBar .nav-list a", function() {
        return ce.log.info("subnav clicked");
      });
      $(document).on("click", ".pjaxLinks a", function(ev) {
        ce.log.info("topnav clicked");
        return ev.preventDefault();
      });
      $(".navbar .nav li a").pjax({
        container: "#page"
      });
      $(".projectBar .nav-list a").pjax({
        container: ".contentBar"
      });
      $(document).on("ajax:success", function() {
        return ce.log.info("ajax:success");
      }).on("pjax:success", function() {
        return ce.log.info("pjax:success");
      });
      $(".contentBar").live("pjax:start", function(ev) {});
      $(".contentBar").on("pjax:end", function(ev) {
        var $el, $grandparent, $parent;
        $el = $(ev.relatedTarget.parentElement);
        $parent = $el.parent();
        $grandparent = $parent.parent();
        $(".projectBar .nav-list li").removeClass("active").removeClass("open");
        $el.addClass("active");
        if ($parent.hasClass("subnav")) {
          $grandparent.addClass("open");
        }
        $el.addClass("open");
        if ($el.has(".subnav")) {
          return $parent.addClass("open");
        }
      });
      return $.bind("ajax:success", function(xhr, data, status) {
        return ce.log.dir(data);
      });
    });
  });

}).call(this);
