// Generated by CoffeeScript 1.3.3

ce.module("_core.pagers", function(self, ce, Backbone, Marionette, $, _, models) {
  self.clientPeople = Backbone.Paginator.clientPager.extend({
    initialize: function() {},
    paginator_core: {
      type: 'post',
      dataType: 'json',
      url: '/people/loadData'
    },
    paginator_ui: {
      firstPage: 1,
      currentPage: 1,
      perPage: 15
    },
    parse: function(response) {
      this.totalPages = Math.ceil(response.length / this.perPage);
      return response;
    },
    model: models.Person
  });
  return self.requestPeople = Backbone.Paginator.requestPager.extend({
    initialize: function() {},
    paginator_core: {
      type: 'post',
      dataType: 'json',
      url: '/people/loadData'
    },
    paginator_ui: {
      firstPage: 1,
      currentPage: 1,
      perPage: 15
    },
    parse: function(response) {
      this.totalPages = Math.ceil(response.length / this.perPage);
      return response;
    },
    model: models.Person
  });
}, ce._core.models);
