// Generated by CoffeeScript 1.3.3

ce.module("_core.views.people", function(self, ce, Backbone, Marionette, $, _) {
  return self.EditView = Backbone.Marionette.ItemView.extend({
    template: "people/edit"
  });
});
