// Generated by CoffeeScript 1.3.3

ce.module("_core.views.activity_cdc", function(self, ce, Backbone, Marionette, $, _) {
  return self.EditView = Backbone.Marionette.ItemView.extend({
    template: "activity_cdc/edit"
  });
});
