// Generated by CoffeeScript 1.3.3

ce.module("Collections", function(self, ce, Backbone, Marionette, $, _) {
  return self.Activities = Backbone.Collection.extend({
    url: '/activities/',
    model: ce.Models.Activity
  });
});
