// Generated by CoffeeScript 1.3.3

ce.module("Collections", function(self, ce, Backbone, Marionette, $, _) {
  return self.Activity_participants = Backbone.Collection.extend({
    url: '/activity_participants/',
    model: ce.Models.Activity_participant
  });
});
