// Generated by CoffeeScript 1.3.3

ce.module("_core.collections", function(self, ce, Backbone, Marionette, $, _, models) {
  return self.Activity_participants = Backbone.Collection.extend({
    url: '/activity_participants/',
    model: models.Activity_participant
  });
}, ce._core.models);
