// Generated by CoffeeScript 1.3.3

ce.module("Collections", function(self, ce, Backbone, Marionette, $, _) {
  return self.Assets = Backbone.Collection.extend({
    url: '/assets/',
    model: ce.Models.Asset
  });
});
