// Generated by CoffeeScript 1.3.3

ce.module("_core.Collections", function(self, ce, Backbone, Marionette, $, _) {
  return self.Main = Backbone.Collection.extend({
    url: '/main/',
    model: ce.Models.Main
  });
});
