// Generated by CoffeeScript 1.3.3

ce.module("_core.Collections", function(self, ce, Backbone, Marionette, $, _) {
  return self.People = Backbone.Collection.extend({
    url: '/people/',
    model: ce.Models.Person
  });
});
