// Generated by CoffeeScript 1.3.3

ce.module("_core.collections", function(self, ce, Backbone, Marionette, $, _, models) {
  return self.Sessions = Backbone.Collection.extend({
    url: '/sessions/',
    model: models.Session
  });
}, ce._core.models);
