// Generated by CoffeeScript 1.3.3

ce.module("ui", function(self, ce, Backbone, Marionette, $, _) {
  self.Loader = Backbone.View.extend({
    template: "ui-loader",
    className: "loader",
    initialize: function() {
      self.on("loader_start", this.start, this);
      self.on("loader_stop", this.stop, this);
    },
    render: function() {
      var _temp;
      _temp = _.template(ce.templates.get(this.template));
      this.$el.prepend(_temp);
      self.trigger("loader_loaded");
    },
    start: function() {
      this.render();
      self.trigger("loader_started");
    },
    stop: function() {
      $("." + this.className).remove();
      self.trigger("loader_stopped");
    }
  });
});
