// Generated by CoffeeScript 1.3.3
var ce;

window.ce = window.ce || {};

ce = new Backbone.Marionette.Application();

ce.module("_core");

ce.module("activity");

ce.module("person");

ce.addRegions({
  page: "#page",
  subpage: ".contentBar div.content-container"
});

ce.addInitializer(function(options) {
  return debug.info("init: app");
});
