// Generated by CoffeeScript 1.3.3

ce.module("creditinator", function(self, ce, Backbone, Marionette, $, _, models, log) {
  self.load = function(params) {
    return self.trigger("loaded");
  };
  return self.on("loaded", function() {
    return log.info("activity: loaded");
  });
}, ce._core.models, ce.log);
