// Generated by CoffeeScript 1.3.3

ce.module("global", function(self, ce, Backbone, Marionette, $, _) {
  var StatusCount, SubmitForm, getResources, getSprites, listHistory, prettyDate, renderHistoryItem;
  SubmitForm = function(oForm) {
    return oForm.submit();
  };
  getResources = function() {
    return getSprites();
  };
  getSprites = function() {
    var resources;
    resources = [];
    if ($("[class^=\"icon16-\"],[class*=\" icon16-\"]").length) {
      $("[class^=\"icon16-\"],[class*=\" icon16-\"]").each(function(i, val) {
        var classes;
        classes = $(this).attr("class").split(" ");
        return $(classes).each(function(i, val) {
          if (val !== "") {
            return resources.push(val);
          }
        });
      });
      resources = resources.unique().sort();
      return $.ajax({
        url: "/assets/sprites/",
        type: "post",
        data: {
          images: resources
        },
        success: function(data) {
          return $("head").append("<link rel=\"stylesheet\" href=\"/stylesheets/sprites/" + $.trim(data) + ".css\" type=\"text/css\" />");
        }
      });
    }
  };
  prettyDate = function(time) {
    var date, day_diff, diff;
    date = new Date((time || "").replace(/-/g, "/").replace(/[TZ]/g, " "));
    diff = ((new Date()).getTime() - date.getTime()) / 1000;
    day_diff = Math.floor(diff / 86400);
    if (isNaN(day_diff) || day_diff < 0 || day_diff >= 31) {
      return $.DateFormat(date, "mmm dd, yyyy");
    }
    return day_diff === 0 && (diff < 60 && "just now" || diff < 120 && "1 minute ago" || diff < 3600 && Math.floor(diff / 60) + " minutes ago" || diff < 7200 && "1 hour ago" || diff < 86400 && Math.floor(diff / 3600) + " hours ago") || day_diff === 1 && "Yesterday" || day_diff < 7 && day_diff + " days ago" || day_diff < 31 && Math.ceil(day_diff / 7) + " weeks ago";
  };
  listHistory = function(appendTo, params, inject) {
    var output;
    output = "";
    return $.ajax({
      url: "/admin/_com/ajax_history.cfc?method=list",
      dataType: "json",
      type: "GET",
      data: params,
      success: function(data, textStatus, XMLHttpRequest) {
        return $.each(data.DATASET, function(i, item) {
          var $historyitem;
          $historyitem = "";
          if (inject === "append") {
            appendTo.append(renderHistoryItem(item));
            $historyitem = $("#history-item-" + item.HISTORYID);
            $historyitem.show();
          } else if (inject === "prepend") {
            appendTo.prepend(renderHistoryItem(item));
            $historyitem = $("#history-item-" + item.HISTORYID);
            $historyitem.fadeIn();
          }
          $historyitem.find(".history-meta a").prettyDate();
          $historyitem.find(".prettydate").prettyDate();
          setInterval((function() {
            return $historyitem.find(".history-meta a").prettyDate();
          }), 5000);
          return setInterval((function() {
            return $historyitem.find(".prettydate").prettyDate();
          }), 5000);
        });
      }
    });
  };
  renderHistoryItem = function(row) {
    var $item, ReturnContent, ToContent, aFoundFields, re, sOutput;
    re = /%[A-Za-z]+%/g;
    ReturnContent = row.TEMPLATEFROM;
    aFoundFields = ReturnContent.match(re);
    sOutput = "";
    ToContent = "";
    $.each(aFoundFields, function(i, item) {
      var VarName;
      ReturnContent = ReturnContent.replace(item, item.toUpperCase());
      VarName = $.trim($.Replace(item, "%", "", "ALL")).toUpperCase();
      return ReturnContent = $.Replace(ReturnContent, VarName, eval_("row." + VarName.toUpperCase()), "ALL");
    });
    ToContent = $.Replace(row.TOCONTENT, "/index.cfm/event/", sMyself, "ALL");
    $item = $("<div/>").addClass("uiStoryItem").attr({
      id: "uiStoryItem-" + row.HISTORYID
    });
    sOutput = "<div class=\"history-item clearfix\" id=\"history-item-" + row.HISTORYID + "\" style=\"display:none;\">" + "<div class=\"history-line clearfix\"><a class=\"uiImage-i\" href=\"/person/general?personId=" + row.FROMPERSONID + "\"><img src=\"" + row.FROMPERSONIMAGE + "\" border=\"0\" /></a>" + ReturnContent + "</div>";
    if (ToContent) {
      sOutput = sOutput + "<div class=\"mvm plm history-subbox\">" + ToContent + "<div style=\"clear:both;\"></div>" + "</div>";
    }
    sOutput = sOutput + "<div class=\"history-meta\"><a title=\"" + row.CREATED + "\">" + row.CREATED + "</a></div>" + "</div>";
    sOutput = $.Replace(sOutput, "%", "", "ALL");
    return sOutput;
  };
  StatusCount = 0;
  $(function() {
    getResources();
    $("input").keydown(function(e) {
      if (e.keyCode === 13) {
        $(this).parents("form").submit();
        return false;
      }
    });
    return $(".dialogLink").on("click", function(e) {
      var $href, $options, $settings, $this;
      $this = $(this);
      $href = $this.attr("href");
      $options = $this.attr("data-options");
      $settings = {
        open: function(event, ui) {
          return $.ajax({
            url: $href
          });
        }
      };
      return $.dialog($options);
    });
  });
  Array.prototype.unique = function() {
    var arrVal, i, uniqueArr, val;
    arrVal = this;
    uniqueArr = [];
    i = arrVal.length;
    while (i--) {
      val = arrVal[i];
      if ($.inArray(val, uniqueArr) === -1) {
        uniqueArr.unshift(val);
      }
    }
    return uniqueArr;
  };
  if (typeof jQuery !== "undefined") {
    jQuery.fn.prettyDate = function() {
      return this.each(function() {
        var date;
        date = prettyDate(this.title);
        if (date) {
          return jQuery(this).text(date);
        }
      });
    };
  }
  return $(function() {
    $("input").keydown(function(e) {
      if (e.keyCode === 13) {
        $(this).parents("form").submit();
        return false;
      }
    });
    $("input.DatePicker").mask("99/99/9999");
    $("#date1").mask("99/99/9999");
    $("#date2").mask("99/99/9999");
    $("#date3").mask("99/99/9999");
    $("#date4").mask("99/99/9999");
    $("#date5").mask("99/99/9999");
    $("#date6").mask("99/99/9999");
    $("#date7").mask("99/99/9999");
    $("#date8").mask("99/99/9999");
    $("#date9").mask("99/99/9999");
    $("#date10").mask("99/99/9999");
    $("#date11").mask("99/99/9999");
    $("#date12").mask("99/99/9999");
    $(".AppDate").mask("99/99/9999");
    $("#phone1").mask("(999) 999-9999");
    $("#phone2").mask("(999) 999-9999");
    $("#phone3").mask("(999) 999-9999");
    $("#phone4").mask("(999) 999-9999");
    $("#phone5").mask("(999) 999-9999");
    $("#phone6").mask("(999) 999-9999");
    $("#phone7").mask("(999) 999-9999");
    $("#phone8").mask("(999) 999-9999");
    $("#fax1").mask("(999) 999-9999");
    $("#fax2").mask("(999) 999-9999");
    $("#tin").mask("99-9999999");
    return $("#ssn").mask("9999");
  });
});
