// Generated by CoffeeScript 1.3.3

ce.module("user", function(self, ce, Backbone, Marionette, $, _, models) {
  self.Model = models.Person.extend({});
  self.load = function(params) {
    self.model = new self.Model(params);
    self.trigger("loaded");
  };
  $(function() {
    $(".loginLink").click(function(ev) {
      self.login({});
      ev.preventDefault();
      return false;
    });
  });
}, ce._core.models);
