// Generated by CoffeeScript 1.3.3

ce.module("_core.models", function(self, ce, Backbone, Marionette, $, _) {
  return self.Activity_participant = Backbone.Model.extend({
    url: "/Activity_participants/"
  });
});
