// Generated by CoffeeScript 1.3.3

ce.module("_core.models", function(self, ce, Backbone, Marionette, $, _) {
  return self.Activity_participant = Backbone.Model.extend({
    url: function() {
      var base;
      base = "/api/activity_participants/";
      if (this.isNew()) {
        return base;
      } else {
        return base + this.id;
      }
    }
  });
});
