// Generated by CoffeeScript 1.3.3

ce.module("ui", function(self, ce, Backbone, Marionette, $, _) {
  self.on("loader_loaded", function() {
    ce.log.info("loader: loaded");
  });
  self.on("loader_started", function() {
    ce.log.info("loader: started");
  });
  return self.on("loader_stopped", function() {
    ce.log.info("loader: stopped");
  });
});
